"""conversation context store

Revision ID: 6febccd6a53b
Revises: 
Create Date: 2026-08-04 12:55:53.529638
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6febccd6a53b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_kind', sa.Enum('ANONYMOUS', name='owner_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('owner_principal_id', sa.Uuid(), nullable=False),
    sa.Column('next_user_turn_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('next_user_turn_no >= 1', name='ck_conversations_turn_no'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_turns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('client_turn_id', sa.Uuid(), nullable=False),
    sa.Column('user_turn_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED', 'CANNOT_ANSWER', 'NEEDS_CLARIFICATION', 'FAILED', name='turn_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('resolution_status', sa.Enum('RESOLVED', 'AMBIGUOUS', 'UNRESOLVED', name='resolution_status', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('resolution_reason_code', sa.String(length=64), nullable=True),
    sa.Column('standalone_query', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('response_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'client_turn_id', name='uq_turn_client_id'),
    sa.UniqueConstraint('conversation_id', 'user_turn_no', name='uq_turn_user_no')
    )
    op.create_index(op.f('ix_conversation_turns_conversation_id'), 'conversation_turns', ['conversation_id'], unique=False)
    op.create_table('grounded_focuses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.String(length=256), nullable=False),
    sa.Column('node_type', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=True),
    sa.Column('canonical_label', sa.Text(), nullable=False),
    sa.Column('document_id', sa.String(length=256), nullable=False),
    sa.Column('article_id', sa.String(length=256), nullable=True),
    sa.Column('clause_id', sa.String(length=256), nullable=True),
    sa.Column('document_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_grounded_user_turn_no', sa.Integer(), nullable=False),
    sa.Column('citation_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'node_id', name='uq_focus_conv_node')
    )
    op.create_index(op.f('ix_grounded_focuses_conversation_id'), 'grounded_focuses', ['conversation_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('turn_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='message_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('kind', sa.Enum('USER_QUERY', 'ANSWER', 'CANNOT_ANSWER', 'CLARIFICATION', 'SMALL_TALK', name='message_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['conversation_turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'ordinal', name='uq_message_ordinal')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_turn_id'), 'conversation_messages', ['turn_id'], unique=False)
    op.create_table('pending_clarifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('source_turn_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('SELECT', 'RESTATE', name='clarification_mode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_turn_id'], ['conversation_turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', name='uq_pending_conversation')
    )
    op.create_table('message_citations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.String(length=256), nullable=False),
    sa.Column('citation_ordinal', sa.Integer(), nullable=False),
    sa.Column('citation_label', sa.Text(), nullable=False),
    sa.Column('document_id', sa.String(length=256), nullable=False),
    sa.Column('article_id', sa.String(length=256), nullable=True),
    sa.Column('clause_id', sa.String(length=256), nullable=True),
    sa.Column('deep_link', sa.Text(), nullable=False),
    sa.Column('metadata_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['conversation_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'unit_id', name='uq_citation_message_unit')
    )
    op.create_index(op.f('ix_message_citations_conversation_id'), 'message_citations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_citations_message_id'), 'message_citations', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_citations_message_id'), table_name='message_citations')
    op.drop_index(op.f('ix_message_citations_conversation_id'), table_name='message_citations')
    op.drop_table('message_citations')
    op.drop_table('pending_clarifications')
    op.drop_index(op.f('ix_conversation_messages_turn_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_grounded_focuses_conversation_id'), table_name='grounded_focuses')
    op.drop_table('grounded_focuses')
    op.drop_index(op.f('ix_conversation_turns_conversation_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_table('conversations')
    # ### end Alembic commands ###
